name: .NET-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./WatchOnlyBitcoinWallet.sln --no-restore -c Release
    - name: Test
      run: dotnet test ./Tests/Tests.csproj --no-build --verbosity normal -c Release

  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./WatchOnlyBitcoinWallet.sln --no-restore -c Release
    - name: Test
      run: dotnet test ./Tests/Tests.csproj --no-build --verbosity normal -c Release
      
  Mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./WatchOnlyBitcoinWallet.sln --no-restore -c Release
    - name: Test
      run: dotnet test ./Tests/Tests.csproj --no-build --verbosity normal -c Release
